### ISSUE TITLE
[GTCEu recipe bug]

### ISSUE THREAD

**Issue by whatsapp2** [LordDarthDan/Unvalkyried-Heavens#1]
Hi, just coming from curseforge to open a proper issue in Github

I saw you mentioned GTCE... GTCE stopped further development and some devs redid the code from scratch, the result is "GregTech Community Edition unofficial" (GTCEu), code is cleaner, has more features overall and is actively working on updates, here's their repository:
 
https://github.com/GregTechCEu/GregTech

It has the same exact issue with Valkyrien Skies, but unlike GTCE, you can probably reach out to their developers in an easier way.

**Comment by LordDarthDan** [comment]
Literally same issue though.
I am looking at this right now, and while yes, the GTCEu devs might be more willing to interact, I'll leave that to you should you want to do so, meanwhile I'll implement a wider patch that works via a config and would potentially cover other mods that bug out in a similar way.

**Comment by LordDarthDan** [comment]
Please check if this build works for you @whatsapp2 
[VS1-GTCEu-compat.zip](https://github.com/LordDarthDan/Unvalkyried-Heavens/files/10522612/VS1-GTCEu-compat.zip)

You can still reach out to GTCEu and see if they wanna solve it on their side if you want, it might give marginally better performance even, but this should solve the problem regardless.

**Comment by LordDarthDan** [comment]
Should fix:
ValkyrienSkies/Valkyrien-Skies-2#385
GregTechCE/GregTech#1450

**Comment by whatsapp2** [comment]
Getting a crash when accessing the GTCEu Multiblock preview
Here's the crash report:
[crash-2023-01-27_14.42.17-client.txt](https://github.com/LordDarthDan/Unvalkyried-Heavens/files/10523034/crash-2023-01-27_14.42.17-client.txt)

**Comment by LordDarthDan** [comment]
Why does it even try to raytrace them?~
Anyway, I'll take a look.

**Comment by LordDarthDan** [comment]
[VS1-GTCEu-compat2.zip](https://github.com/LordDarthDan/Unvalkyried-Heavens/files/10523221/VS1-GTCEu-compat2.zip)
Here's my second attempt to fix this.
If any further problems arise, do tell, at that point I'll just reassemble your pack from the last log and see what's up.

**Comment by whatsapp2** [comment]
Still getting a crash with the Multiblock Preview, however the recipes for machines in VS and GTCEu are showing up fine

**Comment by whatsapp2** [comment]
[crash-2023-01-27_15.29.19-server.txt](https://github.com/LordDarthDan/Unvalkyried-Heavens/files/10523275/crash-2023-01-27_15.29.19-server.txt)

**Comment by LordDarthDan** [comment]
I'll look into this one further tomorrow.

**Comment by LordDarthDan** [comment]
Didn't crash for me, but lagged out the game.
Fixed, now shows the multiblock previews smoothly:
[VS1-GTCEu-compat3.zip](https://github.com/LordDarthDan/Unvalkyried-Heavens/files/10526858/VS1-GTCEu-compat3.zip)


Please check if this works for you as well, and if so, I'll be pushing the fix to Curseforge.

**Comment by whatsapp2** [comment]
Amazingly... It works! Thanks a lot for fixing the issue. If I do encounter any other problem with this .jar I'll let you know, but so far is stable.

**Comment by LordDarthDan** [comment]
Good. I'll push the changes.

**Comment by Alice-Lilith** [comment]
This is fantastic, and works like a charm so far with GTCEU. I was not expecting to find a fix after my issue was closed in the valkyrien skies github. 🙌

**Comment by LordDarthDan** [comment]
> This is fantastic, and works like a charm so far with GTCEU. I was not expecting to find a fix after my issue was closed in the valkyrien skies github. 🙌

Thank you for your report, whatsapp2 posted it on this project's Curseforge page, and that's how I was able to find the issue.

BTW, @whatsapp2 @AliceProxy , this fix is now available on Curseforge as the 1.0.9 release.
