### ISSUE TITLE
Crash when trying to add covers to machines.

### ISSUE THREAD

**Issue by Homssu** [LordDarthDan/Unvalkyried-Heavens#2]
Hey, I decided to give this mod a try because I saw it mentioned a fix for GregTech. Always wanted to have a mobile GT base lol.
Anyways, I experienced a crash when trying to add a conveyor to a macerator that was on an assembled ship, though it seems to crash with any cover and any machine. It only crashes if the ship is assembled.
Here's the crash log when i tried to add an LV conveyor to an LV macerator:
[crash-2023-02-06_22.12.29-client.txt](https://github.com/LordDarthDan/Unvalkyried-Heavens/files/10668863/crash-2023-02-06_22.12.29-client.txt)
I used version 1.0.9 of Unvalkyried Heavens, version 2.5.0-beta of GTCEu, version 1.0.0 of Valkyrien Skies World, Version 1.1.1 of Valkyrien Skies Control

**Comment by LordDarthDan** [comment]
Thanks for bringing this to my attention.
Your log is obfuscated for some reason:
`	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
`
Can be anything and I'm not sure what to make of it.
Could you please try and reproduce it with some mod that can deobfuscate logs installed, like VanillaFix or NormalASM?
Thank you.

**Comment by Homssu** [comment]
Sure thing!
Here's the crash log with NormalASM installed:
[crash-2023-02-13_12.55.04-client.txt](https://github.com/LordDarthDan/Unvalkyried-Heavens/files/10721463/crash-2023-02-13_12.55.04-client.txt)

**Comment by LordDarthDan** [comment]
> Sure thing! Here's the crash log with NormalASM installed: [crash-2023-02-13_12.55.04-client.txt](https://github.com/LordDarthDan/Unvalkyried-Heavens/files/10721463/crash-2023-02-13_12.55.04-client.txt)

Have you reported this to GTCEu yet? I don't immediately see any functions VS would modify. Perhaps this one is easier to resolve on their side?

**Comment by Homssu** [comment]
Alright, opened an issue on their side.
https://github.com/GregTechCEu/GregTech/issues/1505

**Comment by LordDarthDan** [comment]
Assumed resolved on GTCEu side:
https://github.com/GregTechCEu/GregTech/issues/1505#issuecomment-1436126522

Please confirm so I can close this.

**Comment by Homssu** [comment]
Yes, I can add a cover to a machine now, no more crashing.
